version: '3.1'

services:
  db:
    image: postgres:13.7
    privileged: true
    restart: always
    ports:
      - 54324:5432
    environment:
      POSTGRES_DB: 'base'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'